//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int BaiVietId { get; set; }
        public string MaBaiViet { get; set; }
        public int CreatedById { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string NoiDung { get; set; }
        public string AnhDaiDien { get; set; }
        public int TrangThai { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
