//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int ChiTietDonHangId { get; set; }
        public int DonHangId { get; set; }
        public int SanPhamId { get; set; }
        public string TenSanPhamSnapshot { get; set; }
        public decimal DonGiaSnapshot { get; set; }
        public int SoLuong { get; set; }
        public decimal GiamGiaSnapshot { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
