//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTraHang
    {
        public int ChiTietTraHangId { get; set; }
        public int YeuCauId { get; set; }
        public int ChiTietDonHangId { get; set; }
        public int SoLuongTra { get; set; }
        public string LyDoChiTiet { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual YeuCauTraHang YeuCauTraHang { get; set; }
    }
}
