//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int DanhGiaId { get; set; }
        public int ChiTietDonHangId { get; set; }
        public int KhachHangId { get; set; }
        public int SanPhamId { get; set; }
        public byte SoSao { get; set; }
        public string NoiDung { get; set; }
        public int TrangThai { get; set; }
        public Nullable<int> DuyetBoiId { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string LyDoTuChoi { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
