//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHangChiTiet
    {
        public int GioHangChiTietId { get; set; }
        public int KhachHangId { get; set; }
        public int SanPhamId { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
