//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HanhViNguoiDung
    {
        public long HanhViId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public int SanPhamId { get; set; }
        public string LoaiHanhVi { get; set; }
        public string Nguon { get; set; }
        public string SessionId { get; set; }
        public decimal TrongSo { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
