//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KieuDangMat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KieuDangMat()
        {
            this.QuyTacGoiYKinhs = new HashSet<QuyTacGoiYKinh>();
        }
    
        public int KieuDangMatId { get; set; }
        public string MaKieuDangMat { get; set; }
        public string TenKieuDangMat { get; set; }
        public string MoTa { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyTacGoiYKinh> QuyTacGoiYKinhs { get; set; }
    }
}
