//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KieuDangGong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KieuDangGong()
        {
            this.QuyTacGoiYKinhs = new HashSet<QuyTacGoiYKinh>();
            this.SanPhamKinhProfiles = new HashSet<SanPhamKinhProfile>();
        }
    
        public int KieuDangGongId { get; set; }
        public string MaKieuDangGong { get; set; }
        public string TenKieuDangGong { get; set; }
        public string MoTa { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyTacGoiYKinh> QuyTacGoiYKinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamKinhProfile> SanPhamKinhProfiles { get; set; }
    }
}
