//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuTrangThaiTraHang
    {
        public int LichSuTrangThaiTraHangId { get; set; }
        public int YeuCauTraHangId { get; set; }
        public Nullable<int> TrangThaiCu { get; set; }
        public int TrangThaiMoi { get; set; }
        public Nullable<int> ThayDoiBoiId { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual YeuCauTraHang YeuCauTraHang { get; set; }
    }
}
