//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyTacGoiYKinh
    {
        public int QuyTacId { get; set; }
        public int KieuDangMatId { get; set; }
        public int KieuDangGongId { get; set; }
        public int DiemPhuHop { get; set; }
        public string LyDoGoiY { get; set; }
        public bool IsActive { get; set; }
    
        public virtual KieuDangGong KieuDangGong { get; set; }
        public virtual KieuDangMat KieuDangMat { get; set; }
    }
}
