//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleGoiYKinhTheoMat
    {
        public int RuleId { get; set; }
        public string MaHinhDangMat { get; set; }
        public int KieuGongId { get; set; }
        public int DiemPhuHop { get; set; }
        public string GiaiThich { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual KieuGong KieuGong { get; set; }
    }
}
