//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamKinhProfile
    {
        public int SanPhamKinhProfileId { get; set; }
        public int SanPhamId { get; set; }
        public int KieuDangGongId { get; set; }
        public string GioiTinhPhuHop { get; set; }
        public string ChatLieu { get; set; }
        public string MauSac { get; set; }
        public string PhongCach { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual KieuDangGong KieuDangGong { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
