//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanRememberToken
    {
        public int RememberTokenId { get; set; }
        public int TaiKhoanId { get; set; }
        public string TokenHash { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> RevokedAt { get; set; }
        public string UserAgent { get; set; }
        public string IpAddress { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
