//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCuaHang
    {
        public int ThongTinCuaHangId { get; set; }
        public string TenCuaHang { get; set; }
        public string Hotline { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string MoTaNgan { get; set; }
        public string GioiThieu { get; set; }
        public string Logo { get; set; }
        public string Banner { get; set; }
        public string FacebookUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string ZaloUrl { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
