//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhSachHinh
    {
        public int idHinh { get; set; }
        public string hinhSP { get; set; }
        public string ghiChu { get; set; }
        public string maSP { get; set; }
    
        public virtual sanPham sanPham { get; set; }
    }
}
