//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnLTW2Entities : DbContext
    {
        public DoAnLTW2Entities()
            : base("name=DoAnLTW2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<baiViet> baiViets { get; set; }
        public virtual DbSet<chiTietDonHang> chiTietDonHangs { get; set; }
        public virtual DbSet<danhSachHinh> danhSachHinhs { get; set; }
        public virtual DbSet<donHang> donHangs { get; set; }
        public virtual DbSet<khachHang> khachHangs { get; set; }
        public virtual DbSet<loaiSP> loaiSPs { get; set; }
        public virtual DbSet<nhomTaiKhoan> nhomTaiKhoans { get; set; }
        public virtual DbSet<sanPham> sanPhams { get; set; }
        public virtual DbSet<taiKhoanThanhVien> taiKhoanThanhViens { get; set; }
        public virtual DbSet<thongTinCuaHang> thongTinCuaHangs { get; set; }
        public virtual DbSet<thuongHieu> thuongHieux { get; set; }
    }
}
