//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanPham()
        {
            this.chiTietDonHangs = new HashSet<chiTietDonHang>();
            this.danhSachHinhs = new HashSet<danhSachHinh>();
        }
    
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string hinhDD { get; set; }
        public string moTaTomTat { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public string moTa { get; set; }
        public string taiKhoan { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public Nullable<int> giaBan { get; set; }
        public Nullable<int> giamGia { get; set; }
        public Nullable<int> maLoai { get; set; }
        public string kichThuoc { get; set; }
        public int maThuongHieu { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDonHang> chiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danhSachHinh> danhSachHinhs { get; set; }
        public virtual loaiSP loaiSP { get; set; }
        public virtual thuongHieu thuongHieu { get; set; }
        public virtual taiKhoanThanhVien taiKhoanThanhVien { get; set; }
    }
}
