//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taiKhoanThanhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taiKhoanThanhVien()
        {
            this.baiViets = new HashSet<baiViet>();
            this.sanPhams = new HashSet<sanPham>();
            this.thongTinCuaHangs = new HashSet<thongTinCuaHang>();
        }
    
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string hoDem { get; set; }
        public string tenTV { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public string soDT { get; set; }
        public string email { get; set; }
        public string diaChi { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public string ghiChu { get; set; }
        public Nullable<double> soTien { get; set; }
        public Nullable<int> maNhom { get; set; }
        public string maKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<baiViet> baiViets { get; set; }
        public virtual khachHang khachHang { get; set; }
        public virtual nhomTaiKhoan nhomTaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanPham> sanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thongTinCuaHang> thongTinCuaHangs { get; set; }
    }
}
