//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongTinCuaHang
    {
        public int maThongTin { get; set; }
        public string emailLienHe { get; set; }
        public string soDTLienHe { get; set; }
        public string veCuaHang { get; set; }
        public System.DateTime thoiGian { get; set; }
        public string taiKhoan { get; set; }
        public string diaChiLayHang { get; set; }
    
        public virtual taiKhoanThanhVien taiKhoanThanhVien { get; set; }
    }
}
